const lessonData = {};

lessonData["01_AlexanderFleming.mp3"] = [{
    text: "1. Alexander Fleming. Alexander Fleming was a very smart Scottish doctor who discovered the world’s first antibiotic. In the year 1928, he was studying dangerous bacteria in his messy laboratory. He completely forgot to clean his glass plates before going on a long holiday. When he finally returned, he saw something very strange. A blue mold was growing on one of the dirty plates. Amazingly, the mold was naturally killing all the dangerous bacteria around it. Fleming carefully studied this magical mold and named it penicillin. Before his wonderful discovery, a simple cut on a finger could easily become infected and kill a healthy person. Doctors had absolutely no medicine to stop bad bacterial infections. Penicillin completely changed modern medicine forever. During the Second World War, this amazing medicine safely cured thousands of wounded soldiers who would normally die from terrible infections. Today, because of his brilliant and lucky accident, doctors can easily cure many deadly sicknesses like pneumonia and sore throats. Alexander Fleming is a true medical hero because his amazing discovery has successfully saved hundreds of millions of innocent human lives across the entire world.",
    dict: { "antibiotic": "antibiyotik", "messy": "dağınık", "mold": "küf", "naturally": "doğal olarak", "infected": "enfekte", "cured": "iyileştirdi", "pneumonia": "zatürre" },
    questions: [ {q:"Did Fleming discover the first antibiotic?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he studying dangerous bacteria?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he forget to clean his glass plates?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the blue mold kill the bacteria?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he name the mold penicillin?", a_en:"Yes", a_tr:"Evet"}, {q:"Did penicillin change modern medicine?", a_en:"Yes", a_tr:"Evet"}, {q:"Did it cure wounded soldiers in WWII?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["02_MarieCurie.mp3"] = [{
    text: "2. Marie Curie. Marie Curie was a brilliant scientist from Poland who completely changed physics and modern medicine. In the late 1800s, she began studying strange, invisible energy coming from special rocks. She worked extremely hard with her loving husband, Pierre Curie. Together, they discovered two completely new elements, which they named polonium and radium. Marie bravely invented the word 'radioactivity' to deeply explain this powerful, glowing energy. She was the very first woman to ever win a famous Nobel Prize, and she amazingly won it twice in two different sciences. During the terrible First World War, she deeply wanted to help the brave, wounded soldiers. She successfully invented the very first mobile X-ray machines and put them inside small ambulances. She personally drove these amazing vehicles to the dangerous front lines. Doctors used her wonderful X-ray machines to quickly find hidden bullets inside the soldiers' bodies, saving countless innocent lives. Sadly, because she worked with dangerous radiation for many long years, she eventually became very sick and died. Marie Curie gave her entire brave life to science and wonderfully helped invent modern medical treatments.",
    dict: { "physics": "fizik", "invisible": "görünmez", "elements": "elementler", "bravely": "cesurca", "glowing": "parlayan", "ambulances": "ambulanslar", "radiation": "radyasyon" },
    questions: [ {q:"Was Marie Curie from Poland?", a_en:"Yes", a_tr:"Evet"}, {q:"Did she discover polonium and radium?", a_en:"Yes", a_tr:"Evet"}, {q:"Did she invent the word radioactivity?", a_en:"Yes", a_tr:"Evet"}, {q:"Was she the first woman to win a Nobel Prize?", a_en:"Yes", a_tr:"Evet"}, {q:"Did she win it only once?", a_en:"No", a_tr:"Hayır"}, {q:"Did she invent mobile X-ray machines?", a_en:"Yes", a_tr:"Evet"}, {q:"Did she work with dangerous radiation?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["03_LouisPasteur.mp3"] = [{
    text: "3. Louis Pasteur. Louis Pasteur was a truly amazing French scientist who bravely saved millions of completely innocent human lives. In the middle of the 1800s, people constantly got extremely sick from drinking normal, everyday liquids like cold milk or fresh fruit juice. Nobody truly understood why this terrible sickness happened. Pasteur carefully used a microscope and brilliantly proved that tiny, invisible living bugs called germs were causing the dangerous diseases. To safely fix this massive global problem, he successfully invented a wonderful process beautifully named pasteurization. He smartly discovered that if you gently heat the milk for a short time and then cool it down very quickly, it completely kills the tiny, bad germs without ruining the nice taste. This incredibly brilliant, totally simple idea completely stopped massive, deadly sicknesses all over the world. Furthermore, his amazing germ theory directly led to clean hospitals and the wonderful, fast invention of life-saving medical vaccines. Because of this incredibly smart, brave hero, children can safely drink clean milk and happily live totally long, perfectly healthy, completely happy human lives today.",
    dict: { "liquids": "sıvılar", "invisible": "görünmez", "germs": "mikroplar", "pasteurization": "pastörizasyon", "heat": "ısıtmak", "vaccines": "aşılar" },
    questions: [ {q:"Was Louis Pasteur a French scientist?", a_en:"Yes", a_tr:"Evet"}, {q:"Did people get sick from drinking cold milk?", a_en:"Yes", a_tr:"Evet"}, {q:"Did invisible germs cause the diseases?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he invent pasteurization?", a_en:"Yes", a_tr:"Evet"}, {q:"Does pasteurization ruin the nice taste?", a_en:"No", a_tr:"Hayır"}, {q:"Did his germ theory lead to clean hospitals?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he save millions of human lives?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["04_EdwardJenner.mp3"] = [{
    text: "4. Edward Jenner. Edward Jenner was a very smart English doctor who wonderfully invented the very first medical vaccine. During the 1700s, a terrible disease called smallpox was killing millions of innocent people all over the entire world. It was an extremely scary, highly contagious sickness that left terrible scars on the skin. Jenner carefully noticed something very interesting in his quiet country town. He saw that women who milked cows often caught a very weak, safe illness called cowpox. Amazingly, these women never caught the deadly smallpox. In the year 1796, he bravely decided to do a famous experiment. He took a tiny amount of the safe cowpox and gently put it into a healthy young boy’s arm. A few weeks later, he exposed the boy to the terrible smallpox. Wonderfully, the young boy stayed perfectly healthy and totally safe. The weak cowpox successfully taught the boy's body exactly how to fight the deadly disease. Jenner called his brilliant new idea a vaccine. Because of his amazing, brave work, doctors eventually completely destroyed the terrible smallpox disease forever, saving countless millions of lives.",
    dict: { "vaccine": "aşı", "smallpox": "çiçek hastalığı", "contagious": "bulaşıcı", "scars": "yara izleri", "cowpox": "inek çiçeği", "exposed": "maruz bıraktı" },
    questions: [ {q:"Did Edward Jenner invent the first medical vaccine?", a_en:"Yes", a_tr:"Evet"}, {q:"Was smallpox a terrible disease?", a_en:"Yes", a_tr:"Evet"}, {q:"Did women who milked cows often catch cowpox?", a_en:"Yes", a_tr:"Evet"}, {q:"Did cowpox keep them safe from smallpox?", a_en:"Yes", a_tr:"Evet"}, {q:"Did Jenner put cowpox into a healthy boy's arm?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the boy stay perfectly healthy?", a_en:"Yes", a_tr:"Evet"}, {q:"Did doctors eventually destroy smallpox forever?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["05_AntonieVanLeeuwenhoek.mp3"] = [{
    text: "5. Antonie van Leeuwenhoek. Antonie van Leeuwenhoek was a brilliant Dutch businessman who surprisingly became the true father of modern microbiology. In the 1600s, he totally loved making completely perfect, highly curved glass lenses. He cleverly used these tiny, perfect lenses to build the very first practical, powerful microscopes. Before his truly amazing invention, human beings completely believed that nothing existed if it was totally too small for the normal eye to see. Leeuwenhoek completely changed this false belief. He happily looked at everything through his tiny microscopes, including dirty pond water, human blood, and even the plaque from his own teeth. Amazingly, he discovered a completely hidden, massive universe full of tiny moving creatures. He proudly called them 'animalcules,' which we now clearly know as bacteria and living cells. He was the very first person in human history to actually see these tiny, invisible germs and write careful notes about them. Without his brilliant, wonderful microscopes, modern doctors would absolutely never understand how serious diseases work, and we would completely lack all modern medicines and healthy biological science today.",
    dict: { "microbiology": "mikrobiyoloji", "curved": "kavisli", "practical": "pratik/kullanışlı", "existed": "var oldu", "invisible": "görünmez", "biological": "biyolojik" },
    questions: [ {q:"Was Leeuwenhoek a Dutch businessman?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he build the first practical microscopes?", a_en:"Yes", a_tr:"Evet"}, {q:"Did people believe things existed if they were too small to see?", a_en:"No", a_tr:"Hayır"}, {q:"Did he look at dirty pond water?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he discover a universe of tiny moving creatures?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he call them animalcules?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he the first person to see invisible germs?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["06_JohannesGutenberg.mp3"] = [{
    text: "6. Johannes Gutenberg. Johannes Gutenberg is one of the most important inventors in human history. He was born in Germany, and in the year 1440, he completely changed the world by inventing the mechanical printing press. Before his amazing invention, people had to write every single book by hand using a pen. This process was incredibly slow, very difficult, and made books extremely expensive. Only very rich people or powerful churches could afford to buy them. Gutenberg created a brilliant system using small metal letters that he could move around and use many times. He put thick black ink on the metal letters and pressed them firmly onto large, empty pages. Suddenly, workers could print hundreds of books in just one single day. This beautiful machine made books much cheaper and allowed normal people to finally learn how to read and write. Ideas about science, medicine, and human rights spread very quickly across the entire world. Without Gutenberg’s printing press, we would not have modern schools or libraries today. His wonderful machine is the true beginning of our modern age of global communication.",
    dict: { "mechanical": "mekanik", "printing press": "matbaa makinesi", "expensive": "pahalı", "ink": "mürekkep", "firmly": "sıkıca", "communication": "iletişim" },
    questions: [ {q:"Was Gutenberg born in Germany?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he invent the mechanical printing press?", a_en:"Yes", a_tr:"Evet"}, {q:"Were books very cheap before his invention?", a_en:"No", a_tr:"Hayır"}, {q:"Did he use small metal letters?", a_en:"Yes", a_tr:"Evet"}, {q:"Could workers print hundreds of books in one day?", a_en:"Yes", a_tr:"Evet"}, {q:"Did books become much cheaper?", a_en:"Yes", a_tr:"Evet"}, {q:"Did ideas spread very quickly across the world?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["07_JamesWatt.mp3"] = [{
    text: "7. James Watt. James Watt was a brilliant engineer from Scotland who completely changed the modern world. In the late 1700s, he greatly improved the design of the heavy steam engine. Before Watt started working, factories completely relied on weak horses, blowing wind, or running rivers to move their large machines. Early steam engines existed, but they were very slow, extremely weak, and wasted too much hot coal. Watt carefully studied these old machines and added a separate, cold water container to the main engine. This simple but incredibly smart change made the steam engine much stronger, much faster, and completely reliable. Because of his amazing invention, businesses could finally build massive, loud factories anywhere they wanted, not just right next to cold rivers. His powerful engines were soon used to safely pull heavy trains across the country and quickly push large metal ships across the dangerous oceans. Watt’s beautiful steam engine officially started the great Industrial Revolution. It permanently changed how humans travel, how we work in factories, and how we quickly manufacture the important daily products we use right now.",
    dict: { "improved": "geliştirdi", "steam engine": "buhar motoru", "relied on": "güvendi/bel bağladı", "reliable": "güvenilir", "manufacture": "üretmek" },
    questions: [ {q:"Was James Watt an engineer from Scotland?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he improve the heavy steam engine?", a_en:"Yes", a_tr:"Evet"}, {q:"Were early steam engines very fast?", a_en:"No", a_tr:"Hayır"}, {q:"Did he add a separate cold water container?", a_en:"Yes", a_tr:"Evet"}, {q:"Did his change make the engine stronger and faster?", a_en:"Yes", a_tr:"Evet"}, {q:"Were steam engines used to pull heavy trains?", a_en:"Yes", a_tr:"Evet"}, {q:"Did his engine start the Industrial Revolution?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["08_KarlBenz.mp3"] = [{
    text: "8. Karl Benz. Karl Benz was a wonderful German engineer who gave the world true personal freedom. In the year 1885, he successfully invented the very first real automobile powered by a loud gasoline engine. Before his amazing invention, people only traveled by riding slow horses, sitting in heavy wooden wagons, or walking long distances. Benz wanted to create a small, fast machine that a single person could easily drive anywhere. He built a beautiful, three-wheeled vehicle using strong metal pipes, thick rubber tires, and a single-cylinder engine that he carefully designed himself. His smart wife, Bertha Benz, famously took the very first long road trip in history to prove to the whole world that the car actually worked safely. Soon, people realized that this new machine was completely amazing. Karl Benz officially started the massive global car industry. His brilliant invention eventually led to the modern streets, long highways, and millions of fast vehicles we clearly see today. Because of Karl Benz, normal human beings can quickly travel long distances and easily explore the beautiful world whenever they truly want.",
    dict: { "automobile": "otomobil", "gasoline": "benzin", "distances": "mesafeler", "rubber tires": "kauçuk lastikler", "safely": "güvenle" },
    questions: [ {q:"Did Karl Benz invent the first real automobile?", a_en:"Yes", a_tr:"Evet"}, {q:"Was it powered by a gasoline engine?", a_en:"Yes", a_tr:"Evet"}, {q:"Did it have three wheels?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he design the engine himself?", a_en:"Yes", a_tr:"Evet"}, {q:"Did his wife take the first long road trip?", a_en:"Yes", a_tr:"Evet"}, {q:"Did she prove the car worked safely?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he start the global car industry?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["09_ThomasEdison.mp3"] = [{
    text: "9. Thomas Edison. Thomas Edison was a wonderful American inventor who finally brought bright, safe light into our dark world. In the year 1879, he successfully created the very first practical and completely safe electric light bulb. Before his amazing invention, people had to use dangerous fire to carefully light their homes and dark city streets. They used dirty candles, heavy oil lamps, or bad-smelling gas lights. These old lights often caused terrible, destructive house fires and created very dirty smoke. Edison tested thousands of different, thin materials in his laboratory before he finally found the perfect piece of bamboo string. He put the thin string inside a clean, empty glass bulb and safely pushed electricity through it. The beautiful bulb glowed brightly and lasted for many long hours. Suddenly, factories could safely stay open all night, and families could easily read books comfortably in the dark evenings. Edison did not just invent the simple bulb; he also built the large electrical power stations that safely sent invisible electricity directly into people's homes, officially starting the bright, glowing modern age.",
    dict: { "light bulb": "ampul", "dangerous": "tehlikeli", "candles": "mumlar", "destructive": "yıkıcı", "bamboo": "bambu", "glowed": "parladı" },
    questions: [ {q:"Did Thomas Edison create the first safe electric light bulb?", a_en:"Yes", a_tr:"Evet"}, {q:"Did people use dirty candles before his invention?", a_en:"Yes", a_tr:"Evet"}, {q:"Did old lights often cause house fires?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he use a piece of bamboo string?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the bulb glow brightly for many hours?", a_en:"Yes", a_tr:"Evet"}, {q:"Could families read comfortably in the dark evenings?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he also build electrical power stations?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["10_NikolaTesla.mp3"] = [{
    text: "10. Nikola Tesla. Nikola Tesla was a brilliant engineer from Serbia who completely changed how we safely use electricity every single day. In the late 1880s, he successfully developed the Alternating Current, or AC, electrical system. During that time, Thomas Edison was strongly promoting a different system called Direct Current. Edison’s system was very weak and could only send electricity for a few short miles. It required many loud, dirty power stations built right inside the busy city. Tesla’s amazing AC system was completely different and much smarter. It could safely push massive amounts of electrical power over hundreds of long miles without losing any strong energy. Because of Tesla's wonderful invention, we can easily build large power plants far away near big waterfalls or open mountains and safely send the electricity directly into busy towns. Today, every single house, large school, and bright hospital in the entire world completely relies on Tesla’s brilliant AC system to instantly turn on the lights, easily watch television, and quickly charge modern mobile phones. He is truly the father of our modern electrical grid.",
    dict: { "Alternating Current": "Alternatif Akım", "promoting": "teşvik ediyordu/destekliyordu", "required": "gerektiriyordu", "waterfalls": "şelaleler", "relies on": "güvenir/bağlıdır" },
    questions: [ {q:"Was Nikola Tesla an engineer from Serbia?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he develop the Alternating Current (AC) system?", a_en:"Yes", a_tr:"Evet"}, {q:"Was Thomas Edison promoting Direct Current?", a_en:"Yes", a_tr:"Evet"}, {q:"Was Edison's system very strong?", a_en:"No", a_tr:"Hayır"}, {q:"Could Tesla's system send power over hundreds of miles?", a_en:"Yes", a_tr:"Evet"}, {q:"Did it lose a lot of energy?", a_en:"No", a_tr:"Hayır"}, {q:"Do we use Tesla's AC system in our houses today?", a_en:"Yes", a_tr:"Evet"} ]
}];lessonData["11_AlexanderGrahamBell.mp3"] = [{
    text: "11. Alexander Graham Bell. Alexander Graham Bell was a very famous scientist who gave the world the wonderful gift of the human voice. In the year 1876, he successfully invented the very first working telephone. Bell was originally a dedicated teacher who helped deaf people learn how to communicate. He was deeply fascinated by how sound softly travels through the open air. He wanted to find a clever way to send a real human voice over a long electrical wire. After many difficult years of hard work in his laboratory, he finally built a successful machine. The very first famous words he ever spoke through his new device were to his helpful assistant, saying, 'Mr. Watson, come here, I want to see you.' Before the telephone, people could only use the telegraph, which only sent short clicking sounds. Bell’s amazing invention allowed friends, loving families, and busy businesses to instantly talk directly to each other, even if they lived in completely different cities. His brilliant telephone forever changed global communication and directly led to the amazing modern mobile cellphones we absolutely need today.",
    dict: { "dedicated": "kendini adamış", "deaf": "sağır", "fascinated": "büyülenmiş", "device": "cihaz", "assistant": "asistan", "telegraph": "telgraf", "instantly": "anında" },
    questions: [ {q:"Did Alexander Graham Bell invent the first working telephone?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he originally a teacher who helped deaf people?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he want to send a human voice over a wire?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he speak to his assistant first?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the telegraph send real human voices?", a_en:"No", a_tr:"Hayır"}, {q:"Did his invention allow people in different cities to talk instantly?", a_en:"Yes", a_tr:"Evet"}, {q:"Did his telephone lead to modern cellphones?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["12_OrvilleAndWilburWright.mp3"] = [{
    text: "12. Orville and Wilbur Wright. Orville and Wilbur Wright were two very smart American brothers who finally taught human beings exactly how to fly. They originally owned a simple, quiet bicycle shop, but they deeply dreamed of flying high into the beautiful, open sky. Many smart people had already tried to build large flying machines, but they all crashed terribly. The brothers spent many long years carefully studying large birds and testing small, wooden models in a special wind tunnel they built themselves. They finally understood that a successful flying machine needed a powerful, light engine and a completely new way to steer carefully in the rushing wind. On December 17, 1903, they finally tested their famous airplane on a windy, cold beach. Orville successfully flew the strange wooden machine for twelve short seconds. It was the very first powered, controlled human flight in all of world history. Their amazing, brilliant invention completely changed everything. Today, because of these two brave, smart brothers, millions of normal people can safely fly across massive, deep oceans and easily visit different foreign countries in just a few short hours.",
    dict: { "bicycle shop": "bisiklet dükkanı", "crashed": "düştü/çarpıştı", "wind tunnel": "rüzgar tüneli", "steer": "yönlendirmek", "flight": "uçuş", "foreign": "yabancı" },
    questions: [ {q:"Were Orville and Wilbur Wright American brothers?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they originally own a bicycle shop?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they build a wind tunnel to test wooden models?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they fly their airplane on a hot, sunny beach?", a_en:"No", a_tr:"Hayır"}, {q:"Did Orville fly the machine for twelve seconds?", a_en:"Yes", a_tr:"Evet"}, {q:"Was it the first powered, controlled human flight?", a_en:"Yes", a_tr:"Evet"}, {q:"Did their invention completely change how humans travel?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["13_TimBernersLee.mp3"] = [{
    text: "13. Tim Berners-Lee. Tim Berners-Lee is a brilliant English computer scientist who successfully made the huge internet completely easy for everyone to use. In the year 1989, he officially invented the very famous World Wide Web. Before his truly amazing, smart invention, the early internet was extremely difficult and totally boring. It was simply a confusing, dark place for strict scientists to share plain, ugly text files using highly complicated, difficult computer codes. Tim completely changed this totally frustrating system. He brilliantly invented beautifully clickable web links, standard web pages, and the very first simple internet browser. Suddenly, normal, everyday people could easily click a colorful, simple link and instantly visit a completely different page full of beautiful pictures and highly useful information. He bravely gave his completely amazing, world-changing invention to the whole world completely for free. Because of his incredible, generous gift, we can happily shop online, easily play fun video games with distant friends, and quickly search for deeply important information. He wonderfully brought the massive, rich library of human knowledge directly into our cozy, quiet homes.",
    dict: { "confusing": "kafa karıştırıcı", "complicated": "karmaşık", "frustrating": "sinir bozucu", "clickable": "tıklanabilir", "browser": "tarayıcı", "generous": "cömert", "knowledge": "bilgi" },
    questions: [ {q:"Did Tim Berners-Lee invent the World Wide Web?", a_en:"Yes", a_tr:"Evet"}, {q:"Was the early internet very easy and fun to use?", a_en:"No", a_tr:"Hayır"}, {q:"Did he invent clickable web links and web pages?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he sell his invention for millions of dollars?", a_en:"No", a_tr:"Hayır"}, {q:"Did he give the World Wide Web to the world for free?", a_en:"Yes", a_tr:"Evet"}, {q:"Can everyday people easily use the internet today because of him?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he bring a massive library of knowledge into our homes?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["14_FritzHaber.mp3"] = [{
    text: "14. Fritz Haber. Fritz Haber was a highly brilliant German chemist who incredibly saved billions of normal people from terrible, painful hunger. In the very early 1900s, the human population was quickly growing way too fast. Farmers completely lacked enough natural fertilizer to quickly grow the massive amounts of healthy wheat and corn that the world desperately needed. People were deeply terrified of global starvation. Haber successfully invented a completely magical, brilliant chemical process. He discovered exactly how to pull invisible, useless nitrogen gas straight out of the thin air and completely turn it into powerful, solid ammonia fertilizer. This truly amazing, scientific miracle allowed busy farmers to quickly grow incredibly huge amounts of healthy food on very small, poor pieces of land. Today, more than half of all the normal people living on our beautiful planet easily survive simply because of Haber’s brilliant, life-saving agricultural invention. Without his smart, wonderful chemical process, our modern world would simply never have enough basic food to safely feed the eight billion hungry people who happily live here today.",
    dict: { "hunger": "açlık", "fertilizer": "gübre", "starvation": "açlıktan ölme", "nitrogen": "azot", "solid": "katı", "agricultural": "tarımsal" },
    questions: [ {q:"Was Fritz Haber a German chemist?", a_en:"Yes", a_tr:"Evet"}, {q:"Did farmers have enough natural fertilizer in the early 1900s?", a_en:"No", a_tr:"Hayır"}, {q:"Did he invent a way to pull nitrogen gas out of the air?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he turn the gas into solid ammonia fertilizer?", a_en:"Yes", a_tr:"Evet"}, {q:"Did his invention help farmers grow huge amounts of food?", a_en:"Yes", a_tr:"Evet"}, {q:"Do more than half of the people today survive because of his invention?", a_en:"Yes", a_tr:"Evet"}, {q:"Would we have enough food to feed eight billion people without him?", a_en:"No", a_tr:"Hayır"} ]
}];

lessonData["15_GalileoGalilei.mp3"] = [{
    text: "15. Galileo Galilei. Galileo Galilei was a completely brilliant Italian scientist who wonderfully opened human eyes to the massive, beautiful universe. In the year 1609, he heard a strange story about a simple new tool that made distant objects look much closer. He quickly used his smart mathematical skills to build his very own, highly powerful telescope. Before his amazing invention, people simply looked at the dark night sky with their weak human eyes. They wrongly believed that the entire universe peacefully moved perfectly around our Earth. Galileo bravely pointed his long, glass telescope directly at the bright, glowing moon and totally proved it had deep, rough mountains. Even more incredibly, he discovered four large, beautiful moons happily spinning around the giant planet Jupiter. This brilliant, mind-blowing discovery completely proved that the Earth naturally travels around the bright sun, not the other way around. Although the powerful government deeply hated his scary new ideas and angrily locked him inside his house, his wonderful, powerful telescope forever changed astronomy and totally started the amazing modern age of advanced space science.",
    dict: { "universe": "evren", "distant": "uzak", "telescope": "teleskop", "rough": "pürüzlü/engebeli", "spinning": "dönen", "astronomy": "astronomi" },
    questions: [ {q:"Was Galileo an Italian scientist?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he build his own highly powerful telescope?", a_en:"Yes", a_tr:"Evet"}, {q:"Did people before him believe the universe moved around the Earth?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he prove the moon had deep, rough mountains?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he discover four moons spinning around Jupiter?", a_en:"Yes", a_tr:"Evet"}, {q:"Did his discoveries prove the sun travels around the Earth?", a_en:"No", a_tr:"Hayır"}, {q:"Was he locked inside his house by the government?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["16_AlessandroVolta.mp3"] = [{
    text: "16. Alessandro Volta. Alessandro Volta was a very famous scientist from Italy who finally gave human beings the amazing ability to clearly control and securely store electricity. In the year 1800, he successfully invented the very first electric battery, which he proudly called the voltaic pile. Before his wonderful invention, scientists could only carefully make tiny, quick sparks of electricity that totally disappeared in just one single second. Volta deeply wanted to easily create a strong, steady flow of useful power. He carefully built a tall, beautiful tower using round pieces of completely different metals, like dark zinc and shiny copper. He separated the flat metal pieces using small, wet pieces of simple cloth. Surprisingly, this smart chemical tower naturally created a very continuous, reliable electrical current. For the very first time in complete human history, scientists finally had a totally steady source of important power to carefully study. Volta’s brilliant early battery directly led to the amazing modern batteries that safely power our bright flashlights, our fast electric cars, and our tiny, helpful mobile phones every single busy day.",
    dict: { "store": "depolamak", "battery": "pil", "sparks": "kıvılcımlar", "steady": "sabit/düzenli", "zinc": "çinko", "copper": "bakır", "continuous": "sürekli" },
    questions: [ {q:"Did Alessandro Volta invent the first electric battery?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he from Italy?", a_en:"Yes", a_tr:"Evet"}, {q:"Could scientists create a steady flow of power before his invention?", a_en:"No", a_tr:"Hayır"}, {q:"Did he use different metals like zinc and copper?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he separate the metal pieces with wet cloth?", a_en:"Yes", a_tr:"Evet"}, {q:"Did his invention create a continuous electrical current?", a_en:"Yes", a_tr:"Evet"}, {q:"Did his battery lead to modern batteries for phones and cars?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["17_MichaelFaraday.mp3"] = [{
    text: "17. Michael Faraday. Michael Faraday was a brilliant English scientist who truly made the modern, mechanical world turn. In the year 1821, he successfully invented the very first simple electric motor. He was a very poor, uneducated man who completely taught himself complex science by carefully reading old books. During his early experiments, he cleverly discovered that if you push invisible electricity through a simple metal wire while holding a heavy magnet, the wire will magically start to spin quickly in a perfect circle. He beautifully proved that you can easily turn electrical energy directly into real, physical, moving power. A decade later, he smartly reversed the process and successfully invented the electric generator, which clearly turns physical movement back into pure electricity. Without Faraday’s amazing, mind-blowing discoveries, we would not have the large power plants that happily give us daily electricity. We also would completely lack the millions of fast electric motors that safely run our cold refrigerators, spin our loud washing machines, and smoothly power our modern factory machines. He is truly a completely brilliant giant of modern science.",
    dict: { "mechanical": "mekanik", "uneducated": "eğitimsiz", "magnet": "mıknatıs", "spin": "dönmek", "reversed": "tersine çevirdi", "generator": "jeneratör" },
    questions: [ {q:"Did Michael Faraday invent the first simple electric motor?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he a very rich, highly educated man?", a_en:"No", a_tr:"Hayır"}, {q:"Did he teach himself science by reading old books?", a_en:"Yes", a_tr:"Evet"}, {q:"Did a wire start to spin when he pushed electricity through it near a magnet?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he turn electrical energy into physical moving power?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he also invent the electric generator?", a_en:"Yes", a_tr:"Evet"}, {q:"Do his discoveries power our refrigerators and washing machines today?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["18_JohnLogieBaird.mp3"] = [{
    text: "18. John Logie Baird. John Logie Baird was a brilliant engineer from Scotland who gave the modern world the amazing gift of moving pictures. In the year 1925, he successfully invented the very first working mechanical television system. Before his wonderful machine, people could only listen to the radio to get the latest news or carefully read the morning newspaper. Baird wanted to find a clever way to securely send live, moving images completely across a long distance. He built his early, strange machine using completely random pieces, including old bicycle lights, empty cardboard boxes, and ordinary sewing needles. Despite the simple, cheap materials, his smart idea actually worked perfectly. He successfully sent a blurry, shaking picture of a young boy's face from one quiet room to another. Just a few short years later, he wonderfully sent the very first live television picture completely across the massive Atlantic Ocean. Baird’s incredible invention officially started the massive global entertainment industry. He totally changed how humans quickly learn the evening news, comfortably watch famous sports, and happily relax together in their cozy family living rooms.",
    dict: { "moving pictures": "hareketli resimler/görüntüler", "cardboard boxes": "karton kutular", "sewing needles": "dikiş iğneleri", "blurry": "bulanık", "entertainment industry": "eğlence sektörü" },
    questions: [ {q:"Was John Logie Baird an engineer from Scotland?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he invent the first working mechanical television system?", a_en:"Yes", a_tr:"Evet"}, {q:"Did people have televisions before 1925?", a_en:"No", a_tr:"Hayır"}, {q:"Did he build his machine using expensive, modern parts?", a_en:"No", a_tr:"Hayır"}, {q:"Did he successfully send a picture of a boy's face to another room?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he later send a live television picture across the Atlantic Ocean?", a_en:"Yes", a_tr:"Evet"}, {q:"Did his invention start the global entertainment industry?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["19_WillisCarrier.mp3"] = [{
    text: "19. Willis Carrier. Willis Carrier was a very smart American engineer who wonderfully solved the terrible problem of extremely hot, sticky summer weather. In the year 1902, he successfully invented the very first modern air conditioning system. A printing company hired him because the hot, wet air in their large factory was ruining their expensive paper and completely destroying their colorful ink. Carrier brilliantly built a large, heavy machine that pushed hot factory air across very cold, wet pipes. This incredibly smart process quickly removed the heavy water from the air and blew cool, dry, perfect wind into the large room. His wonderful machine totally fixed the terrible printing problem. Very quickly, people smartly put his amazing cooling machines inside dark movie theaters, busy office buildings, and quiet family homes. Because of Carrier’s truly wonderful invention, people can happily live and work comfortably in very hot desert cities all over the wide world. His brilliant machine completely changed modern architecture and wonderfully keeps billions of normal people totally cool, safe, and incredibly happy during the terrible heat of deep summer.",
    dict: { "sticky": "yapışkan", "air conditioning": "klima", "ruining": "mahvediyordu", "ink": "mürekkep", "architecture": "mimari" },
    questions: [ {q:"Did Willis Carrier invent the first modern air conditioning system?", a_en:"Yes", a_tr:"Evet"}, {q:"Did a printing company hire him to fix a problem with hot, wet air?", a_en:"Yes", a_tr:"Evet"}, {q:"Did his machine push hot air across cold pipes?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the machine blow hot, wet air into the room?", a_en:"No", a_tr:"Hayır"}, {q:"Did his invention fix the printing problem?", a_en:"Yes", a_tr:"Evet"}, {q:"Did people put his cooling machines in movie theaters and homes?", a_en:"Yes", a_tr:"Evet"}, {q:"Can people live comfortably in hot desert cities because of him?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["20_GeorgeStephenson.mp3"] = [{
    text: "20. George Stephenson. George Stephenson was a very famous British engineer who completely changed how people travel across land. People proudly call him the father of the modern railway. In the year 1814, he successfully built his very first steam locomotive, which was a heavy train powered by burning hot coal. Before his wonderful invention, transporting heavy goods or large groups of people was extremely slow and very expensive. Horses could only pull small amounts of weight over bad, muddy roads. Stephenson designed incredibly powerful, heavy metal trains that rolled smoothly on long, straight iron tracks. In 1825, he opened the very first public railway in the entire world. His loud, fast trains could safely pull hundreds of passengers and thousands of heavy products across the country in just a few short hours. This amazing invention connected distant towns, created completely new jobs, and helped the great Industrial Revolution grow incredibly fast. Stephenson’s beautiful steam locomotives officially started the amazing age of global train travel, making the large, wide world feel much smaller and much more deeply connected than ever before.",
    dict: { "railway": "demiryolu", "locomotive": "lokomotif", "transporting": "taşımacılık", "muddy": "çamurlu", "passengers": "yolcular", "connected": "bağladı" },
    questions: [ {q:"Is George Stephenson called the father of the modern railway?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he build his first steam locomotive in 1814?", a_en:"Yes", a_tr:"Evet"}, {q:"Was transporting heavy goods fast and cheap before his invention?", a_en:"No", a_tr:"Hayır"}, {q:"Did he design heavy metal trains that rolled on iron tracks?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he open the first public railway in the world?", a_en:"Yes", a_tr:"Evet"}, {q:"Could his trains pull hundreds of passengers safely?", a_en:"Yes", a_tr:"Evet"}, {q:"Did his invention help the Industrial Revolution grow fast?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["21_SamuelMorse.mp3"] = [{
    text: "21. Samuel Morse. Samuel Morse was a brilliant American inventor who forever changed how humans communicate across long distances. In the 1830s, he successfully helped to invent the electrical telegraph machine. Before this wonderful device, if you completely needed to send a very important message to another city, you had to write a paper letter and send it on a slow horse or a big boat. It often took many long weeks to finally hear any important news. Morse brilliantly used a long, thin metal wire to quickly send invisible electrical signals from one town to another. To make this system work perfectly, he also invented Morse Code. This was a very smart, special language using short and long electrical sounds, called dots and dashes, to carefully represent every single letter of the alphabet. Suddenly, important government news, daily business information, and lovely personal messages could travel hundreds of miles in just a few short seconds. Samuel Morse's wonderful telegraph was the very first step toward modern instant communication, easily opening the direct door for the telephone and the modern internet.",
    dict: { "communicate": "iletişim kurmak", "telegraph": "telgraf", "signals": "sinyaller", "dots and dashes": "noktalar ve çizgiler", "represent": "temsil etmek", "instant": "anında" },
    questions: [ {q:"Did Samuel Morse help invent the electrical telegraph machine?", a_en:"Yes", a_tr:"Evet"}, {q:"Was it very fast to send messages to other cities before the telegraph?", a_en:"No", a_tr:"Hayır"}, {q:"Did Morse use a long metal wire to send electrical signals?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he invent a special language called Morse Code?", a_en:"Yes", a_tr:"Evet"}, {q:"Does Morse Code use short and long sounds called dots and dashes?", a_en:"Yes", a_tr:"Evet"}, {q:"Could messages travel hundreds of miles in a few seconds?", a_en:"Yes", a_tr:"Evet"}, {q:"Was the telegraph the first step toward modern instant communication?", a_en:"Yes", a_tr:"Evet"} ]
}];
